#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SECO_COMMON_BOARD)      +=   board.o
obj-$(CONFIG_SECO_COMMON_USDHC)      +=   usdhc.o
obj-$(CONFIG_SECO_COMMON_PFUZE)      +=   pfuze.o
obj-$(CONFIG_TARGET_SECOMX6) += mx6.o
